# Generated by Django 4.2.9 on 2024-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='name',
            field=models.CharField(default='ex', max_length=120),
            preserve_default=False,
        ),
    ]
